### ISSUE TITLE
Shipping tests in a release tarball

### ISSUE THREAD

**Issue by jsmolic** [toumorokoshi/deepmerge#10]
Hi, can you please include tests in your tarballs, either through pypi or github, doesn't matter which one. Could you also release a new github tag, as the last one is 0.0.5? Thanks

**Comment by toumorokoshi** [comment]
Hello! Can you provide some rationale for keeping the tests?

We accepted a [recent PR](https://github.com/toumorokoshi/deepmerge/pull/8) to remove them. 

Regarding the version, it looks like the tags got a bit out of whack, but a [0.1.1](https://pypi.org/project/deepmerge/0.1.1/) release does exist. I'll try to add those tags back.

**Comment by dvzrv** [comment]
> We accepted a [recent PR](https://github.com/toumorokoshi/deepmerge/pull/8) to remove them.

That PR is about not *installing* the tests during runtime. I guess what @jsmolic is referring to is providing the tests in the sdist tarball (from which users and downstream distributions can build, test and install).

**Comment by toumorokoshi** [comment]
> That PR is about not installing the tests during runtime. I guess what @jsmolic is referring to is providing the tests in the sdist tarball (from which users and downstream distributions can build, test and install).

I see, thanks for the clarification. 

I've modified the build and publishing process a bit since last December, and I've verified that the [tarball now includes the test files](https://pypi.org/project/deepmerge/1.0.1/#files), while the wheel when unzipped does not.

I think this satisfies the ask, so I'll close the ticket, but please ping me if that's not the case.
