### ISSUE TITLE
The merge process may alter the left parameter and not to create new dict.

### ISSUE THREAD

**Issue by icy** [toumorokoshi/deepmerge#28]
Hi,

Does that make sense to emphasize that `merge` will actually modify the existing argument?

I've pretty new to Python and got a big hit when I use the following code

```

## https://pypi.org/project/deepmerge/
deep_merger = deepmerge.Merger(
    # pass in a list of tuple, with the
    # strategies you are looking to apply
    # to each type.
    [(list, ["override"]), (dict, ["merge"]), (set, ["union"])],
    # next, choose the fallback strategies,
    # applied to all other types:
    ["override"],
    # finally, choose the strategies in
    # the case where the types conflict:
    ["override"],
)

result =  deep_merger.merge(foo, bar)
```

The result dict is actually a reference to the left parameter (foo). It makes more sense to me to write this code instead

```
foo =  deep_merger.merge(foo, bar)
```

and to get a very fresh merge result, I had to go with 

```
result = deep_merge.merge(copy.deepcopy(foo),bar)
```

I have looked on our documentation and haven't found any notice or warning. What do you think?

Thanks a lot.

**Comment by toumorokoshi** [comment]
Hello! there is a section in the docs referencing this: https://deepmerge.readthedocs.io/en/latest/guide.html#merges-are-destructive. But I would love a PR that would make the warning even more prominent.

As mentioned in the docs, the choice to make the merge destructive (operate directly on the reference) is intentional: it ensures that you don't have to pay a performance cost to use deepmerge. If you want to make it operate on a copy you can call deepcopy yourself: doing the reverse is difficult (skipping the deepcopy).

IMO it's too late now to go back on that choice - users may already be relying on the behavior. But I'd support a PR that makes deepcopies opt-in behavior.

**Comment by icy** [comment]
Hi @toumorokoshi ,

Thanks for your feedback. My bad I really missed that part of the documentation. I totally understand the choice of the behavior and I am not suggesting to change it. I will look if I can help to improve our documentation.

Thanks again.

**Comment by icy** [comment]
Hi @toumorokoshi ,

It's all clear now. I have submitted a very small patch. Please take a look if that's helpful.

Thanks again and cheers.
